import { lstat, mkdir, readdir, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

export const packageRoot = fileURLToPath(new URL('../', import.meta.url));
export const repoRoot = resolve(packageRoot, '../..');
export const sourceRoot = join(repoRoot, 'skills-src');
export const artifactRoot = join(repoRoot, 'skills');

export function contained(root, path) {
  const rel = relative(resolve(root), resolve(path));
  return (
    rel === '' ||
    (!rel.startsWith(`..${sep}`) &&
      rel !== '..' &&
      !resolve(path).startsWith(`${sep}${sep}`) &&
      !rel.startsWith(sep))
  );
}

export async function files(root, prefix = '') {
  if ((await lstat(root)).isSymbolicLink()) throw new Error(`Symlink root: ${root}`);
  const result = [];
  for (const entry of await readdir(join(root, prefix), { withFileTypes: true })) {
    const path = join(prefix, entry.name);
    if (entry.isSymbolicLink())
      throw new Error(`Symlink is not a distributable resource: ${join(root, path)}`);
    if (entry.isDirectory()) result.push(...(await files(root, path)));
    else if (entry.isFile()) result.push(path.replaceAll(sep, '/'));
    else throw new Error(`Unsupported file: ${path}`);
  }
  return result.sort();
}

async function sourceFile(path) {
  if (
    !contained(await realpath(repoRoot), await realpath(path)) ||
    (await lstat(path)).isSymbolicLink()
  )
    throw new Error(`Escaping or symlink source: ${path}`);
  return readFile(path);
}

async function compose(text, workflow) {
  for (const [marker, name] of text.matchAll(/<!-- contract:([a-z0-9-]+) -->/g)) {
    const contract = (await sourceFile(join(sourceRoot, '_shared', `${name}.md`))).toString('utf8');
    if (contract.includes('<!-- contract:')) throw new Error(`Nested contract: ${name}`);
    text = text.replace(marker, contract.trimEnd());
  }
  return text.replaceAll('<!-- generated:workflow -->', workflow);
}

export async function assemble() {
  const manifest = JSON.parse(await readFile(join(sourceRoot, 'manifest.json'), 'utf8'));
  if (manifest.schemaVersion !== 1 || !manifest.skills)
    throw new Error('Unsupported Skill manifest');
  const contract = await build({
    entryPoints: [join(packageRoot, 'src/core/workflow-contract.ts')],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'node',
    logLevel: 'silent',
  });
  const { WORKFLOW_PHASES } = await import(
    `data:text/javascript;base64,${Buffer.from(contract.outputFiles[0].contents).toString('base64')}`
  );
  const workflow = [
    '### Phase contract',
    '',
    '| Phase | Prerequisite | Completion evidence |',
    '| --- | --- | --- |',
    ...WORKFLOW_PHASES.map(
      ({ phase, requires, produces }) => `| ${phase} | ${requires} | ${produces} |`,
    ),
    '',
    'The CLI persists phase flags; portable Skills establish the same evidence from local artifacts. PR delivery and issue closure require the applicable authorization. Neither consumer resumes the other’s session.',
  ].join('\n');
  const provenance =
    '<!-- Generated by skills:sync; edit canonical sources, not this artifact. -->\n\n';
  const output = new Map();
  const compiled = new Map();
  async function put(path, content) {
    if (output.has(path) && !output.get(path).equals(Buffer.from(content)))
      throw new Error(`Conflicting resource: ${path}`);
    output.set(path, Buffer.from(content));
  }
  for (const [name, resources] of Object.entries(manifest.skills)) {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)) throw new Error(`Invalid skill: ${name}`);
    await put(`skills/${name}/LICENSE.txt`, await readFile(join(repoRoot, 'LICENSE')));
    const entry = (await sourceFile(join(sourceRoot, name, 'SKILL.md.in'))).toString('utf8');
    await put(
      `skills/${name}/SKILL.md`,
      entry.replace(
        '\n---\n',
        '\n---\n\n<!-- Generated by skills:sync; edit skills-src, not this artifact. -->\n',
      ),
    );
    for (const [destination, source] of Object.entries(resources)) {
      const target = `skills/${name}/${destination}`;
      const input = resolve(repoRoot, source);
      if (
        !contained(join(repoRoot, 'skills', name), resolve(repoRoot, target)) ||
        !contained(repoRoot, input)
      )
        throw new Error(`Escaping resource: ${source} -> ${target}`);
      const sourceBytes = await sourceFile(input);
      if (source.endsWith('.entry.mjs')) {
        if (!compiled.has(source)) {
          const bundled = await build({
            entryPoints: [input],
            absWorkingDir: repoRoot,
            bundle: true,
            write: false,
            format: 'esm',
            platform: 'node',
            target: 'node22',
            minify: false,
            legalComments: 'inline',
            banner: {
              js: [
                '// Generated by skills:sync; do not edit this artifact.',
                `// Canonical entry point (Issue Flow repository): ${source}`,
                '// Regenerate: cd packages/issue-flow && npm run skills:sync',
                '// Bundled for standalone execution; module comments identify original sources.',
              ].join('\n'),
            },
            sourcemap: false,
            logLevel: 'silent',
          });
          compiled.set(source, bundled.outputFiles[0].contents);
        }
        await put(target, compiled.get(source));
      } else {
        await put(
          target,
          source.endsWith('.md')
            ? provenance + (await compose(sourceBytes.toString('utf8'), workflow))
            : sourceBytes,
        );
      }
    }
  }
  // Only explicitly marked contracts are composed; no runtime includes or template engine.
  const promptSource = join(packageRoot, 'prompts-src');
  for (const path of await files(promptSource)) {
    const text =
      provenance + (await compose(await readFile(join(promptSource, path), 'utf8'), workflow));
    await put(`packages/issue-flow/prompts/${path.replace(/\.in$/, '')}`, text);
  }
  return output;
}

export async function compare(output) {
  const differences = [];
  for (const [path, bytes] of output) {
    const actual = await readFile(join(repoRoot, path)).catch(() => null);
    if (!actual?.equals(bytes)) differences.push(path);
  }
  for (const root of ['skills', 'packages/issue-flow/prompts']) {
    for (const path of await files(join(repoRoot, root))) {
      if (root === 'skills' && ['README.md', 'AGENTS.md'].includes(path)) continue;
      if (!output.has(`${root}/${path}`)) differences.push(`${root}/${path} (unexpected)`);
    }
  }
  return differences;
}

export async function sync() {
  const output = await assemble(); // Validate every source before changing artifacts.
  for (const root of ['skills', 'packages/issue-flow/prompts']) {
    for (const path of await files(join(repoRoot, root))) {
      if (root === 'skills' && ['README.md', 'AGENTS.md'].includes(path)) continue;
      if (!output.has(`${root}/${path}`)) await rm(join(repoRoot, root, path));
    }
  }
  for (const [path, bytes] of output) {
    const dest = join(repoRoot, path);
    if ((await readFile(dest).catch(() => null))?.equals(bytes)) continue;
    await mkdir(dirname(dest), { recursive: true });
    await writeFile(dest, bytes);
  }
  // Remove now-empty source or artifact directories, never follow links.
  async function prune(root) {
    for (const entry of await readdir(root, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const dir = join(root, entry.name);
      await prune(dir);
      if ((await readdir(dir)).length === 0) await rm(dir, { recursive: true });
    }
  }
  await prune(artifactRoot);
  console.log(`Synchronized ${output.size} resources.`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await sync();
